name: CI
on:
  push:
    tags: '**' 
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn -B verify --no-transfer-progress
      - run: mvn -f ./core org.jacoco:jacoco-maven-plugin:0.8.7:report -Djacoco.dataFile="$(readlink -f ./tests/target/jacoco.exec)"
      - uses: codecov/codecov-action@v3
        with:
          file: ./core/target/site/jacoco/jacoco.xml
          name: codecov
          fail_ci_if_error: true
          verbose: true
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
